USE master
GO
 
--========== TẠO DATABASE  ==========--
CREATE DATABASE QUANLYBANGDIA
ON PRIMARY
(
	NAME = QUANLYBANGDIA_DATA,
	FILENAME = 'T:\Projects\QuanLyBangDia\src\org\buffalocoder\quanlybangdia\resources\database\QUANLYBANGDIA_DATA.MDF',
	SIZE = 5MB,
	MAXSIZE = 20MB, 
	FILEGROWTH = 1MB
)
LOG ON
(
	NAME = QUANLYBANGDIA_LOG,
	FILENAME = 'T:\Projects\QuanLyBangDia\src\org\buffalocoder\quanlybangdia\resources\database\QUANLYBANGDIA_LOG.LDF',
	SIZE = 5MB,
	MAXSIZE = 10MB,
	FILEGROWTH = 1MB
)
GO

USE QUANLYBANGDIA
GO

--========== TẠO BẢNG ==========--
CREATE TABLE THONGTINCANHAN
(
	CMND INT NOT NULL,
	HOTEN NVARCHAR(50) NOT NULL,
	DIENTHOAI VARCHAR(20),
	DIACHI NVARCHAR(100),
	GIOITINH INT NOT NULL,
	CONSTRAINT THONGTINCANHAN_CK_GIOITINH CHECK (GIOITINH IN (0, 1)),
	CONSTRAINT THONGTINCANHAN_PK PRIMARY KEY (CMND)
)
GO

CREATE TABLE KHACHHANG
(
	MAKH INT NOT NULL,
	CMND INT NOT NULL,
	NGAYHETHAN DATE,
	CONSTRAINT KHACHHANG_PK PRIMARY KEY (MAKH),
	CONSTRAINT KHACHHANG_FK FOREIGN KEY (CMND) REFERENCES THONGTINCANHAN (CMND)
)
GO

CREATE TABLE NHANVIEN
(
	MANV INT NOT NULL,
	CMND INT NOT NULL,
	MOTA NVARCHAR(100),
	CONSTRAINT NHANVIEN_PK PRIMARY KEY (MANV),
	CONSTRAINT NHANVIEN_FK FOREIGN KEY (CMND) REFERENCES THONGTINCANHAN (CMND)
)
GO

CREATE TABLE BANGDIA
(
	MABD INT NOT NULL,
	TENBD NVARCHAR(50) NOT NULL,
	HANGSANXUAT NVARCHAR(50) NOT NULL,
	GHICHU NVARCHAR(100),
	DONGIA MONEY NOT NULL,
	TINHTRANG INT,
	THELOAI NVARCHAR(30) NOT NULL,
	CONSTRAINT BANGDIA_PK PRIMARY KEY (MABD),
	CONSTRAINT BANGDIA_CK_TINHTRANG CHECK (TINHTRANG IN (0, 1))
)
GO

CREATE TABLE HOADON
(
	MAHD INT NOT NULL,
	NGAYLAP DATE,
	MAKH INT NOT NULL,
	CONSTRAINT HOADON_PK PRIMARY KEY (MAHD),
	CONSTRAINT HOADON_FK_KHACHHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
)
GO

CREATE TABLE CHITIETHOADON
(
	MAHD INT NOT NULL,
	MABD INT NOT NULL,
	SONGAYDUOCMUON INT NOT NULL,
	SOLUONG INT NOT NULL,
	CONSTRAINT CHITIETHOADON_PK PRIMARY KEY (MAHD),
	CONSTRAINT CHITIETHOADON_FK_BANGDIA FOREIGN KEY (MABD) REFERENCES BANGDIA(MABD)
)
GO

ALTER TABLE KHACHHANG
ADD CONSTRAINT KHACHHANG_DF_NGAYHETHAN DEFAULT DATEADD(YEAR, 3, GETDATE()) FOR NGAYHETHAN
GO

ALTER TABLE BANGDIA
ADD CONSTRAINT BANGDIA_DF_TINHTRANG DEFAULT 1 FOR TINHTRANG
GO

ALTER TABLE HOADON
ADD CONSTRAINT HOADON_DF_NGAYLAP DEFAULT GETDATE() FOR NGAYLAP
GO


--========== VIEW --==========
CREATE VIEW VIEW_THONGTINKHACHHANG AS
SELECT	T.CMND, K.MAKH, HOTEN, DIENTHOAI, DIACHI, GIOITINH, NGAYHETHAN 
FROM	THONGTINCANHAN T INNER JOIN KHACHHANG K
		ON T.CMND = K.CMND
GO

CREATE VIEW VIEW_THONGTINNHANVIEN AS
SELECT	T.CMND, N.MANV, HOTEN, DIENTHOAI, DIACHI, GIOITINH, MOTA
FROM	THONGTINCANHAN T INNER JOIN NHANVIEN N
		ON T.CMND = N.CMND
GO

--========== INSERT ==========--
INSERT INTO THONGTINCANHAN (CMND, HOTEN, DIENTHOAI, DIACHI, GIOITINH)
VALUES (1111, 'CHÓ KHOA', '123456789', 'TP. HCM', 1)

INSERT INTO KHACHHANG (MAKH, CMND)
VALUES (1, 1111)

INSERT INTO NHANVIEN (MANV, CMND, MOTA)
VALUES (1, 1111, 'CHÓ KHOA')

INSERT INTO BANGDIA (MABD, TENBD, HANGSANXUAT, GHICHU, DONGIA, TINHTRANG, THELOAI)
VALUES (111, N'CÂU CHIỆN LÀM NGÀNH CỦA KHOA', N'NGÀNH ENTERTAIMENT', N'CẤM TRẺ EM TRÊN 18+', 5000, 1, N'PHIM TRẺ EM')

INSERT INTO HOADON (MAHD, MAKH)
VALUES (112, 1)

INSERT INTO CHITIETHOADON (MAHD, MABD, SONGAYDUOCMUON, SOLUONG)
VALUES (112, 111, 10, 1)
