USE master
GO
 
--========== TẠO DATABASE  ==========--
CREATE DATABASE QUANLYBANGDIA
ON PRIMARY
(
	NAME = QUANLYBANGDIA_DATA,
	FILENAME = 'F:\Project\QuanLyBangDia\QUANLYBANGDIA_DATA.MDF',
	SIZE = 5MB,
	MAXSIZE = 20MB, 
	FILEGROWTH = 1MB
)
LOG ON
(
	NAME = QUANLYBANGDIA_LOG,
	FILENAME = 'F:\Project\QuanLyBangDia\QUANLYBANGDIA_LOG.LDF',
	SIZE = 5MB,
	MAXSIZE = 10MB,
	FILEGROWTH = 1MB
)
GO

USE QUANLYBANGDIA
GO

--========== TẠO BẢNG ==========--
CREATE TABLE THONGTINCANHAN
(
	CMND VARCHAR(20) NOT NULL,
	HOTEN NVARCHAR(50) NOT NULL,
	DIENTHOAI VARCHAR(20),
	DIACHI NVARCHAR(100),
	GIOITINH INT NOT NULL,
	CONSTRAINT THONGTINCANHAN_CK_GIOITINH CHECK (GIOITINH IN (0, 1)),
	CONSTRAINT THONGTINCANHAN_PK PRIMARY KEY (CMND)
)
GO

CREATE TABLE KHACHHANG
(
	MAKH VARCHAR(10) NOT NULL,
	CMND VARCHAR(20) NOT NULL,
	NGAYHETHAN DATE,
	CONSTRAINT KHACHHANG_PK PRIMARY KEY (MAKH),
	CONSTRAINT KHACHHANG_FK FOREIGN KEY (CMND) REFERENCES THONGTINCANHAN (CMND)
)
GO

CREATE TABLE NHANVIEN
(
	MANV VARCHAR(10) NOT NULL,
	CMND VARCHAR(20) NOT NULL,
	MOTA NVARCHAR(100),
	LOAINV VARCHAR(10) CHECK (LOAINV IN  ('THUONG', 'ADMIN')),
	CONSTRAINT NHANVIEN_PK PRIMARY KEY (MANV),
	CONSTRAINT NHANVIEN_FK FOREIGN KEY (CMND) REFERENCES THONGTINCANHAN (CMND)
)
GO

CREATE TABLE BANGDIA
(
	MABD NVARCHAR(10) NOT NULL,
	TENBD NVARCHAR(50) NOT NULL,
	HANGSANXUAT NVARCHAR(50) NOT NULL,
	GHICHU NVARCHAR(100),
	DONGIA MONEY NOT NULL,
	TINHTRANG INT,
	THELOAI NVARCHAR(30) NOT NULL,
	CONSTRAINT BANGDIA_PK PRIMARY KEY (MABD),
	CONSTRAINT BANGDIA_CK_TINHTRANG CHECK (TINHTRANG IN (0, 1))
)
GO

CREATE TABLE HOADON
(
	MAHD VARCHAR(10) NOT NULL,
	NGAYLAP DATE,
	MAKH VARCHAR(10) NOT NULL,
	CONSTRAINT HOADON_PK PRIMARY KEY (MAHD),
	CONSTRAINT HOADON_FK_KHACHHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
)
GO

CREATE TABLE CHITIETHOADON
(
	MAHD VARCHAR(10) NOT NULL,
	MABD NVARCHAR(10) NOT NULL,
	SONGAYDUOCMUON INT NOT NULL,
	SOLUONG INT NOT NULL,
	CONSTRAINT CHITIETHOADON_PK PRIMARY KEY (MAHD),
	CONSTRAINT CHITIETHOADON_FK_BANGDIA FOREIGN KEY (MABD) REFERENCES BANGDIA(MABD)
)
GO

ALTER TABLE KHACHHANG
ADD CONSTRAINT KHACHHANG_DF_NGAYHETHAN DEFAULT DATEADD(YEAR, 3, GETDATE()) FOR NGAYHETHAN
GO

ALTER TABLE BANGDIA
ADD CONSTRAINT BANGDIA_DF_TINHTRANG DEFAULT 1 FOR TINHTRANG
GO

ALTER TABLE HOADON
ADD CONSTRAINT HOADON_DF_NGAYLAP DEFAULT GETDATE() FOR NGAYLAP
GO


--========== VIEW --==========
CREATE VIEW VIEW_THONGTINKHACHHANG AS
SELECT	T.CMND, K.MAKH, HOTEN, DIENTHOAI, DIACHI, GIOITINH, NGAYHETHAN 
FROM	THONGTINCANHAN T INNER JOIN KHACHHANG K
		ON T.CMND = K.CMND
GO

CREATE VIEW VIEW_THONGTINNHANVIEN AS
SELECT	T.CMND, N.MANV, HOTEN, DIENTHOAI, DIACHI, GIOITINH, MOTA
FROM	THONGTINCANHAN T INNER JOIN NHANVIEN N
		ON T.CMND = N.CMND
GO